# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
      - id: fmt
        name: fmt
        language: system
        types: [file, rust]
        entry: cargo fmt -- --check
        pass_filenames: false

      - id: clippy
        name: clippy
        language: system
        types: [file, rust]
        entry: cargo clippy --bins --all -- -D warnings # Use -D warnings option to ensure the job fails when encountering warnings
        pass_filenames: false

      - id: test
        name: test
        language: system
        types: [file, rust]
        entry: cargo test --lib
        pass_filenames: false

default_language_version:
    python: python3
