[package]
name = "rofd"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.17", features = ["derive", "string"] }
cli-table = "0.4.9"
derive_builder = "0.20.1"
env_logger = "0.11.5"
eyre = "0.6.12"
log = "0.4.22"
pdf = "0.9.0"
quick-xml = { version = "0.36.1", features = ["serde", "serialize"] }
relative-path = "1.9.3"
serde = { version = "1.0.210", features = ["derive"] }
serde_with = "3.9.0"
skia-safe = "0.78.0"
thiserror = "1.0.63"
walkdir = "2.5.0"
xml_dom = "0.2.8"
zip = "2.2.0"
# help-macro = { path = "./help-macro" }


[workspace]
# members = ["help-macro"]
