[package]
name = "xdom"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
minidom = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
eyre = { workspace = true }
serde = { workspace = true, features = ["derive"] }
