[package]
name = "ofd_sign"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
ofd_rw = { workspace = true }

der = { version = "0.7.9", features = ["alloc", "derive", "oid", "std"] }
thiserror = { workspace = true }

[dev-dependencies]
eyre = { workspace = true }
